### ISSUE TITLE
aws_iam_access_key

### ISSUE THREAD

**Issue by ulucinar** [crossplane-contrib/provider-tf-aws#67]
Terraform resource name: aws_iam_access_key
Crossplane Kind: v1alpha1.AccessKey
Terraform doc: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_access_key
CRD doc: https://doc.crds.dev/github.com/crossplane-contrib/provider-tf-aws/iam.aws.tf.crossplane.io/AccessKey/v1alpha1@v0.2.0

**Comment by luebken** [comment]
Similar to https://github.com/crossplane-contrib/provider-tf-aws/issues/112
